# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


version: '2'

services:
  postgres:
    container_name: fabric-explorer-db
    image: hyperledger/explorer-db:0.3.9.1
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    
    environment:
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - DATABASE_DATABASE=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
    
    working_dir: /opt
    # docker exec  fabric-explorer-db /opt/createdb.sh

    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data
      
    ports:
      - 5432:5432