# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

version: '2'

services:
  orderer:
    container_name: orderer${ORDERER_ID}.${DOMAIN}
    image: hyperledger/fabric-orderer:${IMAGE_TAG}
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      #${KAFKA_BROKERS}
      - ORDERER_KAFKA_BROKERS=${KAFKA_BROKERS}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer${ORDERER_ID}.${DOMAIN}/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/${DOMAIN}/orderers/orderer${ORDERER_ID}.${DOMAIN}/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

    extra_hosts:
      - "kafka0:192.168.2.211"
      - "kafka1:192.168.2.212"
      - "kafka2:192.168.2.213"
      - "kafka3:192.168.2.213"

 



