# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer:
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    container_name: peer${PEER_ID}.${PEER_ORG}.${DOMAIN}
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_LOCALMSPID=${PEER_LOCALMSPID}
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ID=peer${PEER_ID}.${PEER_ORG}.${DOMAIN}
      - CORE_PEER_ADDRESS=peer${PEER_ID}.${PEER_ORG}.${DOMAIN}:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=${GOSSIP_BOOTSTRAP}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer${PEER_ID}.${PEER_ORG}.${DOMAIN}:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHIANCODE_LOGGING_LEVEL=INFO
      
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    
    command: peer node start

    ports:
      - 7051:7051  # Grpc
      - 7052:7052  # Peer CLI
      - 7053:7053  # Peer Event
      
    extra_hosts:
      - "orderer0.parcelx.io:192.168.2.211"
      - "orderer1.parcelx.io:192.168.2.212"
      - "orderer2.parcelx.io:192.168.2.213"
      - "peer0.orgEast.parcelx.io:192.168.2.211"
      - "peer1.orgEast.parcelx.io:192.168.2.212"
      - "peer0.orgNorth.parcelx.io:192.168.2.213"
      - "peer1.orgNorth.parcelx.io:192.168.2.214"

    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/${PEER_ORG}.${DOMAIN}/peers/peer${PEER_ID}.${PEER_ORG}.${DOMAIN}/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/${PEER_ORG}.${DOMAIN}/peers/peer${PEER_ID}.${PEER_ORG}.${DOMAIN}/tls:/etc/hyperledger/fabric/tls
      - /data/fabric/peer${PEER_ID}.${PEER_ORG}.${DOMAIN}/production:/var/hyperledger/production
