# the path of th crypto-config yaml
crypto:
  # CRYPTO_CONFIG_PATH are added to the system's environment, can be used in  "network-yaml-path"
  crypto-config-path: "E:/ParcelX/Deployment/bootstrap/gen/fabric-config/crypto-config"

  # the path of fabric go sdk configuration yaml file
  network-yaml-path: "E:/ParcelX/Deployment/bootstrap/gen/go-sdk-config/fabric-orgEast-config.yaml"


# the record of the channel block listens to
record:
  # Record every few seconds
  seconds: 30
  # The path to the height that the channel block listens to
  data-path: "./config/.record.yaml"


# the service of transaction handing
third-service:
  url: "http://localhost:18081"
  version: "/api/v1"
  methods:
    uploadParcel:   "/parcel/upload"
    collect:        "/parcel/report/collect"
    weigh:          "/parcel/weigh"
    sendout:        "/parcel/report/sendout"
    takeoff:        "/parcel/report/takeoff"
    landing:        "/parcel/report/landing"
    clearanceStart: "/parcel/report/clearance/start"
    clearanceEnd:   "/parcel/report/clearance/end"
    clearanceError: "/parcel/report/clearance/error"
    handover:       "/parcel/report/handover"
    delivery:       "/parcel/report/delivery"
    signing:        "/parcel/report/signing"
    stopDelivery:   "/parcel/delivery/stop"

# to listen channels
listen-channels:
  - id: channeldev1
    org: orgEast
    user: User1
    # the block number of channel starting to listen
    from: 0

  - id: channeldev2
    org: orgEast
    user: User1
    # the block number of channel starting to listen
    from: 0